name: Hello-world
run-name: Aprendiendo github actions
on:
  push:
    branches: [ "main" ]

jobs:
  Hello-world:
    runs-on: ubuntu-latest
    
    steps:
      # Clonamos el repositorio 
      - name: Clomamos repositorio
        uses: actions/checkout@v4

      # Instalar go
      - name: Configurar Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.9'          

      # Corremos el script de go
      - name: Correr script
        run: go run main.go
