name: 3 Triggers
run-name: Manejo de 3 Triggers
on:
  # Trigger 1
  issue_comment:
    types: [created, edited]
  # Trigger 2
  pull_request:
    types: [created]
    branches: ["main"]
  # Trigger 3
  push:
    branches: ["main"]

jobs:
  Trigger-1:
    runs-on: ubuntu-latest
    # verifica que sea un issue_comment Y que tenga el objeto pull_request
    if: github.event_name == 'issue_comment' || github.event.issue.pull_request != null
    steps:
      - name: Trigger 1
        run: echo "Se comento una pr"
  Trigger-2:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Trigger 2
        run: echo "Se creo una pr"
  Trigger-3:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Trigger 3
        run: echo "Se subio un cambio a la rama ${{github.ref_name}}"
   