name: Uso de Variables
run-name: Variables
on:
  workflow_dispatch:
    inputs:
      nombre:
        description: "Nombre"
        required: true
        type: string

jobs:
  uso-variables:
    runs-on: ubuntu-latest
    env:
      mensaje: hoy es un dia maravilloso
    steps:
      - name: Uso de Variables
        run: |
          echo "Se ejecuto un: $GITHUB_EVENT_NAME, y este es el mensaje $mensaje"

      - name: Uso de Variables 2
        env:
          NOMBRE_USUARIO: ${{ github.event.inputs.nombre }}
        run: |
          echo "Un gran dia llegara para $NOMBRE_USUARIO"